---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  vars:
    _redis_cli:
      default: redis-cli
      Fedora: valkey-cli

    redis_cli: "{{ _redis_cli[ansible_distribution] | default(_redis_cli['default']) }}"

  tasks:
    # Testing Redis/Valkey functionality - using command module for CLI testing
    - name: Write my_key to redis/valkey
      ansible.builtin.command:
        cmd: "{{ redis_cli }} set my_key my_value"
      changed_when: false

    # Testing Redis/Valkey functionality - using command module for CLI testing
    - name: Read my_key from redis/valkey
      ansible.builtin.command:
        cmd: "{{ redis_cli }} get my_key"
      register: redis_read_my_key_from_redis
      changed_when: false
      failed_when:
        - redis_read_my_key_from_redis.stdout != "my_value"
